### ISSUE TITLE
Complete functionality on form and gather up data and send it to back. PR #158

### ISSUE THREAD

**Issue by orjwan98** [founders-programme-2/howl#137]
relates to issues #78 #33 

- [x] Add handlers/state to input fields in children of parent component `Form`. #147 

- [x] Add a handler to handle file upload. relates to #95 

- [x] Add buttons to Form. PR #158 

- [x] Add handlers to buttons and send data to backend. PR #158
