### ISSUE TITLE
As a user I want a way of searching entries

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/howl#31]
Relates to #16 

- [ ] Main page includes search box
- [ ] User can search by keyword, year
- [ ] Content on page is updated to represent data

Technical
- [ ] Api call is made to Airtable with search queries

Stretch 
- [ ] Autocomplete tags as user searches
