### ISSUE TITLE
Content from form can be captured and sent to Airtable #158

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/howl#33]
Text
- [x] Form posts data to Airtable

Image
- [x] Form uploads image to imgur (or something else)
- [x] link to imgur is sent and stored with rest of data in Airtable
