### ISSUE TITLE
Page - Main page

### ISSUE THREAD

**Issue by teenie-quaggard** [founders-programme-2/howl#37]
Includes:

- [ ] Timeline
- [ ] Buttons to filter timeline results by:
 - [ ] Type
 - [ ] Date
 - [ ] Tag
 - [ ] Category
- [ ] Input to search by keyword
- [ ] Link to about howl
- [ ] Link to WLM brief
- [ ] Link to resource page
- [ ] Link to Contribution page
- [ ] Link to how to use the site
