### ISSUE TITLE
DevOps Guidelines. 

### ISSUE THREAD

**Issue by orjwan98** [founders-programme-2/howl#64]
Responsibilities reference issue #5 

- [x] Setup file Structure. issue #53 

- - [x] Make sure the code is modular e.g server, routes, controllers, queries are all separated. 

-------

- [x] Set up eslint for the project. issue #57 

 - - [x] Backend with Airbnb's linting guide. 
 - - [x] Frontend with react-minimal's linting guide.

-------

- [x] Deployment to Heroku. issue #54 

 - - [x] Take ongoing responsibility to make sure each `feature branch` is merged into the `staging branch` after PRs are reviewed and approved. 
 - - [x] Only merge the `staging branch` with `Master` if the `staging branch` works and is bug free. 
- - [x] Set up env variables and update them accordingly.
